# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateJumlahObat.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 567))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_3.setHorizontalSpacing(25)
        self.gridLayout_3.setVerticalSpacing(40)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.inputJumlah = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputJumlah.sizePolicy().hasHeightForWidth())
        self.inputJumlah.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.inputJumlah.setFont(font)
        self.inputJumlah.setText("")
        self.inputJumlah.setObjectName("inputJumlah")
        self.gridLayout_3.addWidget(self.inputJumlah, 5, 0, 1, 2)
        self.buttonOk = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOk.sizePolicy().hasHeightForWidth())
        self.buttonOk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.buttonOk.setFont(font)
        self.buttonOk.setObjectName("buttonOk")
        self.gridLayout_3.addWidget(self.buttonOk, 7, 0, 1, 1)
        self.labelTanggal = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTanggal.sizePolicy().hasHeightForWidth())
        self.labelTanggal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelTanggal.setFont(font)
        self.labelTanggal.setObjectName("labelTanggal")
        self.gridLayout_3.addWidget(self.labelTanggal, 2, 0, 1, 2)
        self.inputTanggal = QtWidgets.QDateEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTanggal.sizePolicy().hasHeightForWidth())
        self.inputTanggal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.inputTanggal.setFont(font)
        self.inputTanggal.setObjectName("inputTanggal")
        self.gridLayout_3.addWidget(self.inputTanggal, 3, 0, 1, 2)
        self.inputID = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputID.sizePolicy().hasHeightForWidth())
        self.inputID.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.inputID.setFont(font)
        self.inputID.setText("")
        self.inputID.setObjectName("inputID")
        self.gridLayout_3.addWidget(self.inputID, 1, 0, 1, 2)
        self.labelPerubahan = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPerubahan.sizePolicy().hasHeightForWidth())
        self.labelPerubahan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelPerubahan.setFont(font)
        self.labelPerubahan.setObjectName("labelPerubahan")
        self.gridLayout_3.addWidget(self.labelPerubahan, 4, 0, 1, 2)
        self.buttonCancel = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCancel.sizePolicy().hasHeightForWidth())
        self.buttonCancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.buttonCancel.setFont(font)
        self.buttonCancel.setObjectName("buttonCancel")
        self.gridLayout_3.addWidget(self.buttonCancel, 7, 1, 1, 1)
        self.labelIDObat = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIDObat.sizePolicy().hasHeightForWidth())
        self.labelIDObat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelIDObat.setFont(font)
        self.labelIDObat.setObjectName("labelIDObat")
        self.gridLayout_3.addWidget(self.labelIDObat, 0, 0, 1, 2)
        self.inputCacat = QtWidgets.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCacat.sizePolicy().hasHeightForWidth())
        self.inputCacat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.inputCacat.setFont(font)
        self.inputCacat.setObjectName("inputCacat")
        self.gridLayout_3.addWidget(self.inputCacat, 6, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonOk.setText(_translate("MainWindow", "OK"))
        self.labelTanggal.setText(_translate("MainWindow", "Tanggal Kedaluarsa"))
        self.labelPerubahan.setText(_translate("MainWindow", "Perubahan Jumlah"))
        self.buttonCancel.setText(_translate("MainWindow", "CANCEL"))
        self.labelIDObat.setText(_translate("MainWindow", "ID Obat"))
        self.inputCacat.setText(_translate("MainWindow", "Obat cacat"))
